name: Update Proxy Configs

on:
  schedule:
    - cron: '0/45 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create directories
      run: |
        mkdir -p assets
        mkdir -p configs
    
    - name: Run config fetcher
      run: python src/fetch_configs.py
      continue-on-error: true
    
    - name: Convert configs to sing-box format
      run: python src/config_to_singbox.py
    
    - name: Setup Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Commit and push changes
      run: |
        git add -A
        git commit -m "Update proxy configs, stats and reports" || echo "No changes to commit"
        git pull --rebase || echo "No remote changes to rebase"
        git push

